name: footware_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  otp_text_field_v2: ^1.0.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  get_storage: ^2.1.1
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  dart_firebase_functions: ^0.0.1-dev.1
  url_launcher: ^6.0.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_paypal: ^0.2.1
  flutter_braintree: ^4.0.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  uni_links:
    git:
      url: https://github.com/DanMossa/uni_links.git
      ref: dee0e0834c70b4b64e8d26adbb7911b0e0090b96
      path: uni_links # Specify the correct path where the `pubspec.yaml` is located within the repo

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"