name: footware_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  dropdown_button2: ^2.3.9

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

